version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
    reviewers:
      - "bajtos"
    ignore:
      # Keep the `log` crate at version ^0.17.0 to stay compatible with
      # Deno crates that are pinning `log` version exactly to `0.17.0`
      - dependency-name: "log"
      # Pin the `ureq` version. Newer versions break our test case that depends
      # on a specific handling of transfer-encoding:chunked errors used by Lassie.
      # It's a dev-dependency so there is very little risk in staying on an older version.
      - dependency-name: "ureq"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
    reviewers:
      - "bajtos"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "ci"
    reviewers:
      - "bajtos"
