[target.x86_64-unknown-linux-gnu]
pre-build = [
    "rm -rf /usr/local/go && curl -L https://go.dev/dl/go1.20.5.linux-amd64.tar.gz | tar -xz -C /usr/local && ln -s /usr/local/go/bin/go /usr/local/bin/ && go version"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    # Cross is always running the container on `amd64`, therefore you must download `amd64` version
    # of Go when targeting `aarch64`.
    "rm -rf /usr/local/go && curl -L https://go.dev/dl/go1.20.5.linux-amd64.tar.gz | tar -xz -C /usr/local && ln -s /usr/local/go/bin/go /usr/local/bin/ && go version"
]
